project_id = "hlnzunnahksudbotqvpk"

[api]
enabled = true
url = "https://hlnzunnahksudbotqvpk.supabase.co/functions/v1/"

[[functions]]
name = "transcribe"
verify_jwt = false

[[functions]]
name = "gemini"
verify_jwt = false